import { useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { PageHeader } from '../components/common/PageHeader';
import { Button, Card, Avatar } from '../components/ui';
import api from '../api/api';
import { notify } from '../utils/notify';

export default function Attendance() {
  const [students, setStudents] = useState([]); const [status, setStatus] = useState({}); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [cls, setCls] = useState(''); const [section, setSection] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const { data } = await api.get('/teachers/my-students', { params: { limit: 500, ...(cls ? { class: cls } : {}), ...(section ? { section } : {}) } }); const rows = data.data || []; setStudents(rows); setStatus(Object.fromEntries(rows.map((s) => [s._id, 'present']))); } catch (e) { notify.error(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => students.filter((s) => (!cls || s.class === cls) && (!section || s.section === section)), [students, cls, section]);
  const save = async () => { if (!filtered.length) return notify.error('No students found for this class/section'); const className = cls || filtered[0]?.class; const sec = section || filtered[0]?.section; if (!className || !sec) return notify.error('Class and section are required'); setSaving(true); try { await api.post('/attendance/mark', { class: className, section: sec, date, records: filtered.map((s) => ({ student: s._id, status: status[s._id] || 'present' })) }); notify.success('Attendance saved successfully'); } catch (e) { notify.error(e.message); } finally { setSaving(false); } };
  const classes = [...new Set(students.map((s) => s.class).filter(Boolean))]; const sections = [...new Set(students.filter((s) => !cls || s.class === cls).map((s) => s.section).filter(Boolean))];
  return <><Helmet><title>Attendance — Teacher Panel</title></Helmet><PageHeader title="Attendance" subtitle="Mark and save student attendance from the school database." actions={<Button onClick={save} loading={saving}>Save Attendance</Button>} /><Card className="p-4 mb-5 grid grid-cols-1 sm:grid-cols-3 gap-4"><div><label className="form-label">Class</label><select className="form-input" value={cls} onChange={(e) => setCls(e.target.value)}><option value="">All assigned classes</option>{classes.map((x) => <option key={x}>{x}</option>)}</select></div><div><label className="form-label">Section</label><select className="form-input" value={section} onChange={(e) => setSection(e.target.value)}><option value="">All sections</option>{sections.map((x) => <option key={x}>{x}</option>)}</select></div><div><label className="form-label">Date</label><input type="date" className="form-input" value={date} onChange={(e) => setDate(e.target.value)} /></div></Card>{loading ? <Card className="p-8 text-center">Loading students...</Card> : <div className="overflow-x-auto bg-white rounded-xl border border-slate-100"><table className="w-full min-w-[700px]"><thead><tr className="bg-slate-50 text-left text-xs text-slate-500"><th className="p-4">Student</th><th className="p-4">Class</th><th className="p-4">Present</th><th className="p-4">Absent</th><th className="p-4">Late</th><th className="p-4">Leave</th></tr></thead><tbody>{filtered.map((s) => <tr key={s._id} className="border-t border-slate-100"><td className="p-4"><div className="flex items-center gap-3"><Avatar src={s.user?.avatar} name={s.user?.name} size="sm" /><span>{s.user?.name}</span></div></td><td className="p-4">{s.class} - {s.section}</td>{['present','absent','late','leave'].map((x) => <td className="p-4" key={x}><input type="radio" name={`att-${s._id}`} checked={status[s._id] === x} onChange={() => setStatus((v) => ({ ...v, [s._id]: x }))} /></td>)}</tr>)}</tbody></table>{!filtered.length && <div className="p-8 text-center text-slate-500">No students found.</div>}</div>}</>;
}
